# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.

options:

  waltz-db-host:
    type: string
    default: ""
    description: |
      The postgresql database host to be used by Waltz.

  waltz-db-port:
    type: int
    default: 5432
    description: |
      The postgresql database port to be used by Waltz.

  waltz-db-name:
    type: string
    default: "waltz"
    description: |
      The database name to be used by Waltz.

  waltz-db-username:
    type: string
    default: "waltz"
    description: |
      The username used to connect to the postgresql database.

  waltz-db-password:
    type: string
    default: "waltz"
    description: |
      The password used to connect to the psotgresql database.
